### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by equinusocio** [bonsaicss/bonsai.css#10]
Hello, I'm here to ask someone to tell me how/why to use this library. I want to give it a try but I can't figure out the advantages 😕.

After some test I ended up with something like this to make a card

```html
<div style="--maxw:400px; --p:0; --br:5px;">...</div>
```

but how this this can be considered different from classic inline style which doesn't require any lib?

```html
<div style="max-width:400px; padding:0; border-radius:5px">...</div>
```

Each time I have a card I have to copy/paste the whole style attribute over and over, and if I have to change the style of the card I have to do a find/replace and change all the occurrence :(. Also i have to create a class anyway when I need to handle pseudo elements and pseudo selectors.

Can some explain me the difference/advantages?

**Comment by ciar4n** [comment]
Hi!

A couple of key advantages over standard inline styling...

1. Responsive. Bonsai utilities allows you to apply styling for each screensize. Something not possible with standard inline styling (https://www.bonsaicss.com/#responsive-design-and-media-queries).

2. Pseudo-classes. Potentially we can create styling for pseudo class variants (:hover, :focus, :before etc.).

There is some other smaller advantages regarding inheritance which we hope to detail shortly.

> Each time I have a card I have to copy/paste the whole style attribute over and over, and if I have to change the style of the card I have to do a find/replace and change all the occurrence.

For repeated elements, we would always recommend to create your own repeatable, modular CSS. All frameworks have utilities which allow you to apply CSS quickly within your markup. With Bonsai however we rxplore the possibility of offering a complete utility library at as low a file size as possible. I stand to be corrected but I believe Bonsai is currently the smallest utility complete CSS framework.
