### ISSUE TITLE
--fg (flex-grow) not implemented?

### ISSUE THREAD

**Issue by yvesh** [bonsaicss/bonsai.css#18]
Hey @ciar4n,
flex-grow seems not to be implemented (at least when i check the dist version of bonsai.css) - it's mentioned in the documentation (utilities section) though.

Missing code:

```
[style*="--fg:"] {
    flex-grow: var(--fg) !important;
}
```

Thanks,
Yves

**Comment by yvesh** [comment]
Just checked the actual code:

```scss
@mixin svar-mq flex-grow, --fw;
```

[https://github.com/bonsaicss/bonsai.css/blob/master/src/utilities/_flex.css#L9](https://github.com/bonsaicss/bonsai.css/blob/master/src/utilities/_flex.css#L9)

Looks like a typo, and flex-wrap seems to be missing.

Btw. to you prefer opening Issues + PR or should I do a pull request only?

**Comment by ciar4n** [comment]
Thank you Yves... well spotted. PR created and merged.. https://github.com/bonsaicss/bonsai.css/pull/21

An opened issue with a PR would always be much appreciated 👍
