### ISSUE TITLE
[Question] Pseudo-classes: Undocumented or Missing?

### ISSUE THREAD

**Issue by ibn-akbar** [bonsaicss/bonsai.css#19]
I couldn't find pseudo-class support.
Please give a little example if it's implemented.

**Comment by ciar4n** [comment]
Hey @ibn-akbar... good question.

One of the keys goals of Bonsai was to keep filesize to a minimum so initially, I decided to not add pseudo-class utilities. Having said that, I have created a PR (#23) which adds a mixin to allow you to create your own if required.  I would certainly be open to adding some of the more popular properties applied to psuedo-elements by default or even create a separate build specifically for them.
