### ISSUE TITLE
[Idea] Support size better, like small?

### ISSUE THREAD

**Issue by yvesh** [bonsaicss/bonsai.css#24]
Hey @ciar4n,

I know you want to keep it as lightweight as possible, but there are multiple cases where helpers for sizing may be useful (to keep it consistent through multiple elements). For example currently the button spacing is quite "hardcoded":

```css
  padding-right: 28px;
  padding-left: 28px;
  margin: .5rem .5rem .5rem 0;
  padding: 10px 12px;
```

Do you see a way to make this more dynamic (like moving the spacing stuff to variables)?

Or maybe (that's a big maybe), better supporting constructions like:

`<small><button>..</button></small>`

```css
small button {
   /* lower spacing etc. */
}
```

An alternate would be classes, like .btn-small, .btn-lg - But this wouldn't be as dynamic and only focused on button elements :-/

What do you think?

Thanks,
Yves

**Comment by ciar4n** [comment]
Hey Yves

There is an option to create a 'helper' for sizing. The `--size` variable could default to 3 if not present on an element. This variable could effect font-size, padding and margin. An example would look like the following.

```html
<button style="--size:1"> Small Button</button>
```

```html
<button style="--size:3"> Medium Button</button>
```

```html
<button style="--size:5"> Large Button</button>
```

Would you consider this a suitable solution?

**Comment by yvesh** [comment]
:+1: Sounds great and makes even more sense and follows the scheme.

**Comment by ciar4n** [comment]
PR created #24

Unfortunately the `--size` variable is already been used so when with `--x`. Also notched up the default to 100 (basically %) to give some more versatility.
