### ISSUE TITLE
[Issue] -xl is not overwriting -lg / -md

### ISSUE THREAD

**Issue by yvesh** [bonsaicss/bonsai.css#26]
Hey @ciar4n,

not sure if this is intended, but -xl is not overriding -md or -lg elements.

**"Worst case" sample:**
https://codepen.io/yvesh-the-sans/pen/XWKPRXg

It's related to the ordering and !important, either it needs a `max-width` on the media queries (like bootstrap is doing in certain cases) or change the ordering (and remove !important -- ?).

What do you suggest?

Thank you!

**Comment by ciar4n** [comment]
This is indeed an issue and not by design. It appears to be related to the gulp plugin used to combine the media queries. Some media queries are be placed in the wrong order. I will submit a fix shortly. Thank you for posting the issue!
