### ISSUE TITLE
Logical properties

### ISSUE THREAD

**Issue by C-Lodder** [bonsaicss/bonsai.css#30]
Safari are gradually starting to add more support for logical CSS properties, which will assist with RTL.

You can also add support for:

- border-inline-start
- border-inline-end

in https://github.com/bonsaicss/bonsai.css/blob/master/src/utilities/_border.css

**Comment by ciar4n** [comment]
Good point. `border-inline-*` added with #33. I'll follow up with the rest shortly.

**Comment by ciar4n** [comment]
Re-opened until complete.

Far now adding the following I believe would make the most sense.

- padding-inline-start
- padding-inline-end
- margin-inline-start
- margin-inline-end

The likes of `margin-block` have limited support so will leave these till v2. For now they are partially covered with helpers.. https://www.bonsaicss.com/docs/helpers/spacing/
