### ISSUE TITLE
docs?

### ISSUE THREAD

**Issue by brianteeman** [bonsaicss/bonsai.css#4]
Is there a repo for the docs?

I spotted a few references to bedrock in the docs and a lot of errors in the headers

**Comment by ciar4n** [comment]
@brianteeman Thank you for pointing these out. 

Currently, the docs (run on Hugo) are on a private repo. I will make them public once I do some general house cleaning.

**Comment by brianteeman** [comment]
No problem. Let me know if you need to use my proofreading eyes
