### ISSUE TITLE
--shadow is not really box-shadow

### ISSUE THREAD

**Issue by yvesh** [bonsaicss/bonsai.css#59]
Hey @ciar4n,

in the documentation (Utilities) --shadow is described as box-shadow. But it's more a helper for a shadow without any customizations.

What do you think about adding a separate helper for box-shadow? --bs is already taken.

Sample usage:

`--box: 0 0 0 2px var(--primary) inset;`

or

`--boxs: 0 0 0 2px var(--primary) inset;`

**Comment by ciar4n** [comment]
Yes that makes sense. `--shadow` should not be listed under utilities. A `--bs` utlility should exist.
