### ISSUE TITLE
--background-body clearification

### ISSUE THREAD

**Issue by yvesh** [bonsaicss/bonsai.css#61]
in the _body.css on line 14 (https://github.com/bonsaicss/bonsai.css/blob/master/src/base/_body.css#L14) the background for the html tag is set with the variable `--background-body` without a fallback. 

But this one is defined nowhere and is not listed in variables.css. Is there a reason for this? 
`--background `is defined, but not used at this location.

**Comment by ciar4n** [comment]
Well spotted. Looks like an error. Check out #62 for a suggested fix.

**Comment by yvesh** [comment]
@ciar4n Looks fine :+1: Thank you!

// Closed
