### ISSUE TITLE
[Issue] PayPal Button

### ISSUE THREAD

**Issue by yvesh** [bonsaicss/bonsai.css#65]
Maybe the .input and input settings are too generic?

Just tried integrating a PayPal Button (Type doesn't matter) with bonsai.css enabled. Especially because the official paypal markup is weird (to keep it polite).

```html
    <input type="image" name="submit"
    src="https://www.paypalobjects.com/en_US/i/btn/btn_donate_LG.gif"
    alt="Donate">
```
This results in a 100% width unreadable image with a border etc. What do you think does that need fixing from bonsai side?

> Special cases aren't special enough to break the rules?

**Comment by ciar4n** [comment]
I think it is something that could pop up elsewhere so worth considering. Maybe simply #66 ?
