### ISSUE TITLE
Docs mention something called bedrock

### ISSUE THREAD

**Issue by kschmidtdev** [bonsaicss/bonsai.css#8]
In https://www.bonsaicss.com/docs/getting-started/installation/:

"Extract and include the ./dist/bedrock.min.css"

Old project name perhaps? The code snippet underneath has `bonsai.min.css` so I wanted to check what the right one is :) Thanks!

**Comment by ciar4n** [comment]
Thank you @kschmidtdev for bringing this to our attention.

Indeed. The project was originally called Bedrock however due to a name clash it was renamed to Bonsai. This text has been corrected to "Extract and include the ./dist/bonsai.min.css"
